{
 "title": "Ballerina Http Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" },
   { "name": "httpmethod", "label": "http-method", "query": "label_values(http_method)" },
   { "name": "httpurl", "label": "http-url", "query": "label_values(http_url)" },
   { "name": "protocol", "label": "protocol", "query": "label_values(protocol)" },
   { "name": "resource", "label": "resource", "query": "label_values(resource)" },
   { "name": "service", "label": "service", "query": "label_values(service)" },
   {
    "name": "ballerinaaction",
    "label": "ballerina-action",
    "query": "label_values(ballerina_http:Connection_requests_total,action)"
   },
   {
    "name": "clientaction",
    "label": "client-action",
    "query": "label_values(ballerina_http:HttpCachingClient_requests_total,action)"
   },
   { "name": "peerport", "label": "peer-port", "query": "label_values(peer_port)" },
   { "name": "peerhostname", "label": "peer-hostname", "query": "label_values(peer_hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Http Error rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ballerina_http:HttpCachingClient_4XX_requests_total+ballerina_http:HttpCachingClient_5XX_requests_total)*100/sum(ballerina_http:Connection_requests_total)"
    }
   ]
  },
  {
   "title": "Http Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "description": "This is the http response time throughput",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(http_requests_total{instance=~\"$instance\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",protocol=~\"$protocol\",resource=~\"$resource\",service=~\"$service\"}[1m])",
       "legendFormat": "{{instance}}---{{http_method}}--{{http_url}}--{{protocol}}--{{resource}}--{{service}}--1m"
      },
      {
       "expr": "rate(http_requests_total{instance=~\"$instance\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",protocol=~\"$protocol\",resource=~\"$resource\",service=~\"$service\"}[5m])",
       "legendFormat": "{{instance}}---{{http_method}}--{{http_url}}--{{protocol}}--{{resource}}--{{service}}--5m"
      },
      {
       "expr": "rate(http_requests_total{instance=~\"$instance\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",protocol=~\"$protocol\",resource=~\"$resource\",service=~\"$service\"}[15m])",
       "legendFormat": "{{instance}}---{{http_method}}--{{http_url}}--{{protocol}}--{{resource}}--{{service}}--15m"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "description": "This is the http response time of ballerina service",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "http_response_time_seconds{instance=~\"$instance\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",protocol=~\"$protocol\",resource=~\"$resource\",service=~\"$service\"}",
       "legendFormat": "{{instance}}---{{http_method}}--{{http_url}}--{{protocol}}--{{resource}}--{{service}}--{{quantile}}"
      }
     ]
    },
    {
     "title": "Response Time Statistic",
     "type": "graph",
     "description": "Average of http response time",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds{instance=~\"$instance\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",protocol=~\"$protocol\",resource=~\"$resource\",service=~\"$service\"})without(quantile)",
       "legendFormat": "{{instance}}--{{http_method}}--{{http_url}}--{{protocol}}--{{resource}}--{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina Http Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ballerina Client Throughtput",
     "type": "graph",
     "description": "Client response time throughput",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "sum without(http_status_code)(rate(ballerina_http:HttpCachingClient_requests_total{action=~\"$clientaction\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",instance=~\"$instance\",peer_hostname=~\"$peerhostname\",\npeer_port=~\"$peerport\"}[1m]))",
       "legendFormat": "{{instance}}--{{action}}--{{http_method}}--{{http_url}}--{{peer_hostname}}--{{peer_port}}--1m"
      },
      {
       "expr": "sum without(http_status_code)(rate(ballerina_http:HttpCachingClient_requests_total{action=~\"$clientaction\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",instance=~\"$instance\",peer_hostname=~\"$peerhostname\",\npeer_port=~\"$peerport\"}[5m]))",
       "legendFormat": "{{instance}}--{{action}}--{{http_method}}--{{http_url}}--{{peer_hostname}}--{{peer_port}}--5m"
      },
      {
       "expr": "sum without(http_status_code)(rate(ballerina_http:HttpCachingClient_requests_total{action=~\"$clientaction\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",instance=~\"$instance\",peer_hostname=~\"$peerhostname\",\npeer_port=~\"$peerport\"}[15m]))",
       "legendFormat": "{{instance}}--{{action}}--{{http_method}}--{{http_url}}--{{peer_hostname}}--{{peer_port}}--15m"
      }
     ]
    },
    {
     "title": "Ballerina Client Response Time",
     "type": "graph",
     "description": "Client response time",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "sum without(http_status_code)(ballerina_http:HttpCachingClient_response_time_seconds{action=~\"$clientaction\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",instance=~\"$instance\",peer_hostname=~\"$peerhostname\",\npeer_port=~\"$peerport\"})",
       "legendFormat": "{{instance}}--{{action}}--{{http_method}}--{{http_url}}--{{peer_hostname}}--{{peer_port}}--{{quantile}}"
      }
     ]
    },
    {
     "title": "Ballerina Http Client Response Time Statistic",
     "type": "graph",
     "description": "Average of client response time",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds{action=~\"$clientaction\",http_method=~\"$httpmethod\",http_url=~\"$httpurl\",instance=~\"$instance\",peer_hostname=~\"$peerhostname\",\npeer_port=~\"$peerport\"})without(quantile,http_status_code)",
       "legendFormat": "{{instance}}--{{action}}--{{http_method}}--{{http_url}}--{{peer_hostname}}--{{peer_port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina Http Status Code Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "1XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:Connection_1XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:Connection_1XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:Connection_1XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "2XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:Connection_2XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:Connection_2XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:Connection_2XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "3XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:Connection_3XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:Connection_3XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:Connection_3XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "4XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:Connection_4XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:Connection_4XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:Connection_4XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "5XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:Connection_5XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:Connection_5XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:Connection_5XX_requests_total{instance=~\"$instance\",action=~\"$ballerinaaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina Http Client Status Code Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "1XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:HttpCachingClient_1XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_1XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_1XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "2XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:HttpCachingClient_2XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_2XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_2XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "3XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:HttpCachingClient_3XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_3XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_3XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "4XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:HttpCachingClient_4XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_4XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_4XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    },
    {
     "title": "5XX Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "rate(ballerina_http:HttpCachingClient_5XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[1m])",
       "legendFormat": "{{instance}}--{{action}}--1m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_5XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[5m])",
       "legendFormat": "{{instance}}--{{action}}--5m"
      },
      {
       "expr": "rate(ballerina_http:HttpCachingClient_5XX_requests_total{instance=~\"$instance\",action=~\"$clientaction\"}[15m])",
       "legendFormat": "{{instance}}--{{action}}--15m"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Metrics Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Http Response Time by Instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by (instance)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by (instance)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by (http_method)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by (http_method)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Resource",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by(resource)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Protocol",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by(protocol)"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina Http Client Metrics Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Ballerina Http Client Response Time by Action",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (action)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (instance)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (http_method)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Url",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (http_url)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Peer_Hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (peer_hostname)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Peer_Port",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (peer_port)"
      }
     ]
    }
   ]
  }
 ]
}